# Generated by Django 3.0.4 on 2021-01-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imagefile',
            new_name='imagefile1',
        ),
        migrations.AddField(
            model_name='image',
            name='imagefile2',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='image',
            name='imagefile3',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
