# Generated by Django 3.0.4 on 2021-01-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20210121_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='user_name',
        ),
    ]
