# Generated by Django 3.0.4 on 2021-01-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_auto_20210121_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
