# Generated by Django 3.0.4 on 2021-01-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_auto_20210121_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
