# Generated by Django 3.2.3 on 2021-05-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_auto_20210122_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imagefile6',
        ),
    ]
